name: elm-1x1-tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/e3sm-project/containers-ghci:ghci-0.2.1
    steps:
      - name: Test echo
        run: echo "Container is working!"

