name: Manual Test Echo

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test-echo:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/e3sm-project/containers-ghci:ghci-0.2.1
    steps:
      - name: Show branch and test info
        run: |
          echo "Running manual test!"
          echo "Branch: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "These are the tests we would run:"
          echo " - SMS_D_Ln5_P4.ne4pg2_oQU480.F2010.ghci-oci_gnu"
          echo " - ERS_Ld5_P4.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.ghci-oci_gnu.eamxx-prod"

