name: Run 1x1 ELM Test

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    if: ${{ github.repository == 'ORNL-Ecosystem-Projects/E3SM' }}
    strategy:
      fail-fast: false
      matrix:
        test:
          - SMS_Ln10_P1x1.1x1_smallvilleIA.IELMCNCROP.elm-per_crop
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/e3sm-project/containers-ghci:ghci-0.2.1
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          submodules: recursive
      - 
        name: CIME
        working-directory: cime/scripts
        run: |
          ./create_test ${{ matrix.test }} --wait --debug
      - 
        name: Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ matrix.test }}
          path: |
            /projects/e3sm/scratch/${{ matrix.test }}*/TestStatus.log
            /projects/e3sm/scratch/${{ matrix.test }}*/bld/*.bldlog.*
            /projects/e3sm/scratch/${{ matrix.test }}*/run/*.log.*
            /projects/e3sm/scratch/${{ matrix.test }}*/run/*.cprnc.out

